create table "public"."Users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "displayName" text
);


alter table "public"."Users" enable row level security;

CREATE UNIQUE INDEX "Users_id_key" ON public."Users" USING btree (id);

CREATE UNIQUE INDEX "Users_pkey" ON public."Users" USING btree (id);

alter table "public"."Users" add constraint "Users_pkey" PRIMARY KEY using index "Users_pkey";

alter table "public"."Users" add constraint "Users_id_key" UNIQUE using index "Users_id_key";


