create table "public"."synced_playlists" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp without time zone default now(),
    "user_id" text default ''::text,
    "playlist_id" text
);


alter table "public"."synced_playlists" enable row level security;

CREATE UNIQUE INDEX synced_playlist_pkey ON public.synced_playlists USING btree (id);

CREATE UNIQUE INDEX synced_playlist_user_id_key ON public.synced_playlists USING btree (user_id);

alter table "public"."synced_playlists" add constraint "synced_playlist_pkey" PRIMARY KEY using index "synced_playlist_pkey";

alter table "public"."synced_playlists" add constraint "synced_playlist_user_id_key" UNIQUE using index "synced_playlist_user_id_key";

alter table "public"."synced_playlists" add constraint "synced_playlists_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."synced_playlists" validate constraint "synced_playlists_user_id_fkey";


